### ISSUE TITLE
Checkvalve selection

### ISSUE THREAD

**Issue by dtgerson** [RespiraWorks/Ventilator#628] opened 2020-06-04 22:54 UTC
Need to pick a check valve for after the blower

**Comment by martukas** [comment] 2021-01-18 07:55
Currently testing in 0.3 enclosed build with: https://www.mcmaster.com/5492K13/

**Comment by martukas** [comment] 2021-01-18 07:56
Needs to be added to repo BOMs to consider this done

**Comment by martukas** [comment] 2021-01-18 22:11
Appears to be duplicate of #653

**Closed by martukas** 2021-01-18 22:11 UTC
Labels: Mechanical, Pneumatics
